'use client'

import { Button } from '@/components/ui/Button'
import BottomNavigation from '@/components/ui/BottomNavigation'
import { Download, Share2, Calendar, Pill, FileText, Star, Shield, X } from 'lucide-react'
import { useRouter } from 'next/navigation'

// Screen 4: Post-Consultation Summary
export default function ConsultationSummary() {
  const router = useRouter()

  const handleEmergencyClick = () => {
    router.push('/emergency/e1')
  }

  return (
    <div className="h-full bg-gray-50 flex flex-col">
      {/* Status Bar */}
      <div className="flex justify-between items-center px-4 py-1 text-black text-sm bg-gray-50 pt-2">
        <span className="font-medium">9:41</span>
        <div className="flex items-center space-x-1">
          <div className="flex space-x-1">
            <div className="w-1 h-3 bg-black rounded"></div>
            <div className="w-1 h-3 bg-black rounded"></div>
            <div className="w-1 h-3 bg-black rounded"></div>
            <div className="w-1 h-3 bg-black opacity-50 rounded"></div>
          </div>
          <span>📶</span>
          <span>🔋</span>
        </div>
      </div>

      {/* Header */}
      <div className="bg-gradient-to-r from-blue-50 to-cyan-50 px-4 py-6 flex items-center justify-between">
        <div className="flex items-center space-x-3">
          <div className="w-12 h-12 bg-gradient-to-r from-blue-500 to-cyan-500 rounded-2xl flex items-center justify-center">
            <FileText className="w-6 h-6 text-white" />
          </div>
          <div>
            <h1 className="text-lg font-bold text-gray-900">Consultation Summary</h1>
            <p className="text-sm text-blue-600">Post-consultation report</p>
          </div>
        </div>
        <div className="flex items-center space-x-2">
          <Button variant="ghost" size="sm">
            <Download className="w-4 h-4" />
          </Button>
          <button 
            onClick={() => router.back()}
            className="w-10 h-10 bg-gradient-to-r from-pink-200 to-purple-200 rounded-full flex items-center justify-center"
          >
            <X className="w-5 h-5 text-blue-600" />
          </button>
        </div>
      </div>

      <div className="flex-1 px-4 py-2 overflow-y-auto scrollbar-hide pb-20">
        {/* Consultation Info */}
        <div className="bg-white rounded-xl p-4 mb-4 shadow-sm">
          <div className="flex items-center space-x-3 mb-4">
            <div className="w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center">
              👩‍⚕️
            </div>
            <div>
              <h3 className="font-semibold text-gray-900">Dr. Sarah Wilson</h3>
              <p className="text-sm text-gray-600">General Medicine</p>
            </div>
            <div className="ml-auto text-right">
              <p className="text-sm font-medium text-gray-900">15 mins</p>
              <p className="text-xs text-gray-500">Dec 26, 2024</p>
            </div>
          </div>
          
          <div className="bg-green-50 border border-green-200 rounded-lg p-3">
            <div className="flex items-center space-x-2">
              <div className="w-2 h-2 bg-green-500 rounded-full"></div>
              <p className="text-sm font-medium text-green-800">Consultation Completed</p>
            </div>
            <p className="text-xs text-green-600 mt-1">
              Medical summary generated by AI • Reviewed by doctor
            </p>
          </div>
        </div>

        {/* Diagnosis */}
        <div className="bg-white rounded-xl p-4 mb-4 shadow-sm">
          <div className="flex items-center space-x-2 mb-3">
            <FileText className="w-5 h-5 text-blue-500" />
            <h3 className="font-semibold text-gray-900">Diagnosis</h3>
          </div>
          <div className="space-y-2">
            <div className="bg-blue-50 rounded-lg p-3">
              <p className="font-medium text-blue-900">Primary: Gastroesophageal Reflux (GERD)</p>
              <p className="text-sm text-blue-700 mt-1">
                Chest pain likely due to acid reflux. No cardiac concerns detected.
              </p>
            </div>
          </div>
        </div>

        {/* Prescriptions */}
        <div className="bg-white rounded-xl p-4 mb-4 shadow-sm">
          <div className="flex items-center space-x-2 mb-3">
            <Pill className="w-5 h-5 text-blue-500" />
            <h3 className="font-semibold text-gray-900">Prescriptions</h3>
          </div>
          <div className="space-y-3">
            <div className="border border-gray-200 rounded-lg p-3">
              <div className="flex items-start justify-between mb-2">
                <div>
                  <p className="font-medium text-gray-900">Omeprazole 20mg</p>
                  <p className="text-sm text-gray-600">Proton pump inhibitor</p>
                </div>
                <span className="text-xs bg-blue-100 text-blue-700 px-2 py-1 rounded">
                  7 days
                </span>
              </div>
              <p className="text-sm text-gray-600">
                Take 1 tablet daily before breakfast
              </p>
            </div>
            
            <div className="border border-gray-200 rounded-lg p-3">
              <div className="flex items-start justify-between mb-2">
                <div>
                  <p className="font-medium text-gray-900">Antacid Syrup</p>
                  <p className="text-sm text-gray-600">For immediate relief</p>
                </div>
                <span className="text-xs bg-blue-100 text-blue-700 px-2 py-1 rounded">
                  As needed
                </span>
              </div>
              <p className="text-sm text-gray-600">
                2 teaspoons after meals if symptoms persist
              </p>
            </div>
          </div>
          
          <Button 
            variant="outline" 
            className="w-full mt-3"
            onClick={() => {
              // Show success message instead of navigating
              alert('Prescription saved to your LifeLog records successfully!')
            }}
          >
            <FileText className="w-4 h-4 mr-2" />
            Save to LifeLog
          </Button>
        </div>

        {/* Recommendations */}
        <div className="bg-white rounded-xl p-4 mb-4 shadow-sm">
          <h3 className="font-semibold text-gray-900 mb-3">Recommendations</h3>
          <div className="space-y-2">
            <div className="flex items-start space-x-2">
              <div className="w-2 h-2 bg-blue-500 rounded-full mt-2"></div>
              <p className="text-sm text-gray-600">
                Avoid spicy, fatty, and acidic foods
              </p>
            </div>
            <div className="flex items-start space-x-2">
              <div className="w-2 h-2 bg-blue-500 rounded-full mt-2"></div>
              <p className="text-sm text-gray-600">
                Eat smaller, more frequent meals
              </p>
            </div>
            <div className="flex items-start space-x-2">
              <div className="w-2 h-2 bg-blue-500 rounded-full mt-2"></div>
              <p className="text-sm text-gray-600">
                Elevate head while sleeping
              </p>
            </div>
            <div className="flex items-start space-x-2">
              <div className="w-2 h-2 bg-blue-500 rounded-full mt-2"></div>
              <p className="text-sm text-gray-600">
                Follow up if symptoms persist after 1 week
              </p>
            </div>
          </div>
        </div>

        {/* Follow-up */}
        <div className="bg-white rounded-xl p-4 mb-4 shadow-sm">
          <div className="flex items-center space-x-2 mb-3">
            <Calendar className="w-5 h-5 text-blue-500" />
            <h3 className="font-semibold text-gray-900">Follow-up</h3>
          </div>
          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-3">
            <p className="font-medium text-yellow-800">Recommended in 1 week</p>
            <p className="text-sm text-yellow-600 mt-1">
              Schedule if symptoms don't improve with medication
            </p>
          </div>
          <Button variant="outline" className="w-full mt-3">
            <Calendar className="w-4 h-4 mr-2" />
            Schedule Follow-up
          </Button>
        </div>

        {/* Rate Consultation */}
        <div className="bg-white rounded-xl p-4 mb-4 shadow-sm">
          <div className="flex items-center space-x-2 mb-3">
            <Star className="w-5 h-5 text-blue-500" />
            <h3 className="font-semibold text-gray-900">Rate Your Experience</h3>
          </div>
          <div className="flex justify-center space-x-2 mb-3">
            {[1, 2, 3, 4, 5].map((star) => (
              <button key={star} className="p-1">
                <Star className="w-8 h-8 text-yellow-400 fill-current" />
              </button>
            ))}
          </div>
          <textarea
            placeholder="Share your feedback (optional)"
            className="w-full p-3 border border-gray-200 rounded-lg bg-white text-gray-900 text-sm"
            rows={3}
          />
          <Button variant="primary" className="w-full mt-3">
            Submit Rating
          </Button>
        </div>

        {/* Action Buttons */}
        <div className="space-y-3 mb-4">
          <Button 
            variant="primary" 
            size="lg" 
            className="w-full"
            onClick={() => router.push('/docconnect')}
          >
            Book Another Consultation
          </Button>
          
          <Button 
            variant="outline" 
            size="lg" 
            className="w-full"
            onClick={() => router.push('/')}
          >
            Back to Home
          </Button>
        </div>

        {/* Emergency Button */}
        <button
          onClick={handleEmergencyClick}
          className="w-full bg-red-500 hover:bg-red-600 text-white font-bold py-3 rounded-2xl shadow-sm transition-all flex items-center justify-center space-x-2 mb-1"
        >
          <Shield className="w-5 h-5" />
          <span className="text-sm">EMERGENCY</span>
        </button>
      </div>

      <BottomNavigation />
    </div>
  )
}
