'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { Button } from '@/components/ui/Button'
import StatusBar from '@/components/ui/StatusBar'
import AppHeader from '@/components/ui/AppHeader'
import BottomNavigation from '@/components/ui/BottomNavigation'
import { 
  FileText, 
  Edit3, 
  Download, 
  Share2, 
  Save,
  Clock,
  User,
  Tag,
  Star,
  CheckCircle,
  AlertCircle,
  Lightbulb,
  Target,
  Calendar,
  Heart
} from 'lucide-react'

// Screen C3: Session Notes Screen
export default function SessionNotes() {
  const router = useRouter()
  const [isEditing, setIsEditing] = useState(false)
  const [notes, setNotes] = useState('')
  const [personalNotes, setPersonalNotes] = useState('')

  const sessionInfo = {
    title: 'Diabetes Management Workshop',
    instructor: 'Dr. Priya Sharma',
    date: '2024-12-26',
    duration: '90 minutes',
    type: 'Live Workshop',
    category: 'Chronic Care',
    rating: 4.8,
    participants: 47
  }

  const autoGeneratedNotes = `
# Diabetes Management Workshop - Key Points

## Overview
- Type 2 diabetes affects 77 million Indians
- Lifestyle modifications can significantly improve outcomes
- Early intervention is crucial for preventing complications

## Diet Recommendations
### Foods to Include:
- Whole grains (brown rice, quinoa, oats)
- Lean proteins (fish, chicken, legumes)
- Non-starchy vegetables (leafy greens, broccoli, peppers)
- Healthy fats (nuts, seeds, olive oil)

### Foods to Limit:
- Refined sugars and processed foods
- White bread and refined grains
- Sugary beverages
- High-sodium foods

## Exercise Guidelines
- **Aerobic Exercise**: 150 minutes moderate intensity per week
- **Strength Training**: 2-3 sessions per week
- **Daily Activity**: 10,000 steps target
- **Timing**: Exercise 1-2 hours after meals for better glucose control

## Blood Sugar Monitoring
- Check fasting glucose: 80-130 mg/dL
- Post-meal glucose (2 hours): <180 mg/dL
- HbA1c target: <7% for most adults
- Monitor ketones if glucose >250 mg/dL

## Medication Management
- Take medications as prescribed
- Don't skip doses
- Understand hypoglycemia symptoms
- Carry glucose tablets

## Lifestyle Tips
1. **Meal Planning**: Prepare meals in advance
2. **Portion Control**: Use smaller plates
3. **Stress Management**: Practice meditation or yoga
4. **Sleep**: 7-9 hours per night
5. **Hydration**: 8-10 glasses of water daily

## Warning Signs to Watch
- Excessive thirst or urination
- Unexplained weight loss
- Blurred vision
- Slow-healing wounds
- Frequent infections

## Next Steps
- Schedule follow-up with endocrinologist
- Join diabetes support group
- Download glucose tracking app
- Attend nutrition counseling session
  `

  const keyTakeaways = [
    'Diet plays a crucial role in diabetes management',
    'Regular exercise improves insulin sensitivity',
    'Blood sugar monitoring helps track progress',
    'Stress management is essential for glucose control',
    'Early intervention prevents complications'
  ]

  const actionItems = [
    { task: 'Schedule endocrinologist appointment', priority: 'high', completed: false },
    { task: 'Start daily glucose monitoring', priority: 'high', completed: false },
    { task: 'Join local diabetes support group', priority: 'medium', completed: false },
    { task: 'Download recommended tracking app', priority: 'low', completed: true },
    { task: 'Plan weekly meal prep', priority: 'medium', completed: false }
  ]

  const handleSaveNotes = () => {
    // Here you would save the notes to the database
    setIsEditing(false)
  }

  return (
    <div className="h-screen bg-gray-50 flex flex-col overflow-hidden">
      <StatusBar />
      <AppHeader title="Session Notes" subtitle="Workshop Summary And Insights" showProfile={false} />

      <div className="flex-1 px-4 py-2 overflow-y-auto scrollbar-hide min-h-0">
        {/* Session Header */}
        <div className="bg-white dark:bg-gray-800 rounded-xl p-4 mb-6 shadow-sm">
          <div className="flex items-start justify-between mb-4">
            <div className="flex-1">
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">{sessionInfo.title}</h2>
              <div className="flex items-center space-x-4 text-sm text-gray-600 dark:text-gray-300">
                <div className="flex items-center space-x-1">
                  <User className="w-4 h-4" />
                  <span>{sessionInfo.instructor}</span>
                </div>
                <div className="flex items-center space-x-1">
                  <Clock className="w-4 h-4" />
                  <span>{sessionInfo.duration}</span>
                </div>
                <div className="flex items-center space-x-1">
                  <Calendar className="w-4 h-4" />
                  <span>{sessionInfo.date}</span>
                </div>
              </div>
            </div>
            <div className="flex items-center space-x-2">
              <span className="text-xs bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300 px-2 py-1 rounded">
                {sessionInfo.type}
              </span>
              <div className="flex items-center space-x-1">
                <Star className="w-4 h-4 text-yellow-400 fill-current" />
                <span className="text-sm font-medium text-gray-700 dark:text-gray-300">{sessionInfo.rating}</span>
              </div>
            </div>
          </div>
          
          <div className="flex items-center space-x-2">
            <Button
              variant={isEditing ? "primary" : "outline"}
              size="sm"
              onClick={() => setIsEditing(!isEditing)}
            >
              <Edit3 className="w-4 h-4 mr-1" />
              {isEditing ? 'Save Changes' : 'Edit Notes'}
            </Button>
            <Button variant="outline" size="sm">
              <Download className="w-4 h-4 mr-1" />
              Export
            </Button>
            <Button variant="outline" size="sm">
              <Share2 className="w-4 h-4 mr-1" />
              Share
            </Button>
          </div>
        </div>

        {/* Key Takeaways */}
        <div className="bg-white dark:bg-gray-800 rounded-xl p-4 mb-6 shadow-sm">
          <h3 className="font-semibold text-gray-900 dark:text-white mb-4 flex items-center">
            <Lightbulb className="w-5 h-5 mr-2 text-yellow-500" />
            Key Takeaways
          </h3>
          
          <div className="space-y-2">
            {keyTakeaways.map((takeaway, index) => (
              <div key={index} className="flex items-start space-x-2">
                <CheckCircle className="w-4 h-4 text-green-500 mt-0.5" />
                <p className="text-sm text-gray-700 dark:text-gray-300">{takeaway}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Action Items */}
        <div className="bg-white dark:bg-gray-800 rounded-xl p-4 mb-6 shadow-sm">
          <h3 className="font-semibold text-gray-900 dark:text-white mb-4 flex items-center">
            <Target className="w-5 h-5 mr-2 text-blue-500" />
            Action Items
          </h3>
          
          <div className="space-y-3">
            {actionItems.map((item, index) => (
              <div key={index} className="flex items-center space-x-3 p-3 bg-gray-50 dark:bg-gray-700 rounded-lg">
                <input
                  type="checkbox"
                  checked={item.completed}
                  className="w-4 h-4 text-blue-500 rounded"
                />
                <div className="flex-1">
                  <p className={`text-sm ${item.completed ? 'line-through text-gray-500 dark:text-gray-400' : 'text-gray-900 dark:text-white'}`}>
                    {item.task}
                  </p>
                </div>
                <span className={`text-xs px-2 py-1 rounded-full ${
                  item.priority === 'high' ? 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300' :
                  item.priority === 'medium' ? 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-300' :
                  'bg-gray-100 text-gray-700 dark:bg-gray-600 dark:text-gray-300'
                }`}>
                  {item.priority}
                </span>
              </div>
            ))}
          </div>
        </div>

        {/* Auto-Generated Notes */}
        <div className="bg-white dark:bg-gray-800 rounded-xl p-4 mb-6 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-semibold text-gray-900 dark:text-white flex items-center">
              <FileText className="w-5 h-5 mr-2 text-purple-500" />
              Workshop Notes
            </h3>
            <span className="text-xs bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 px-2 py-1 rounded">
              Auto-generated
            </span>
          </div>
          
          {isEditing ? (
            <textarea
              value={notes || autoGeneratedNotes}
              onChange={(e) => setNotes(e.target.value)}
              className="w-full h-96 p-3 border border-gray-200 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm font-mono resize-none focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="Edit the workshop notes..."
            />
          ) : (
            <div className="prose prose-sm max-w-none dark:prose-invert">
              <pre className="whitespace-pre-wrap text-sm text-gray-700 dark:text-gray-300 font-sans">
                {notes || autoGeneratedNotes}
              </pre>
            </div>
          )}
        </div>

        {/* Personal Notes */}
        <div className="bg-white dark:bg-gray-800 rounded-xl p-4 mb-6 shadow-sm">
          <h3 className="font-semibold text-gray-900 dark:text-white mb-4 flex items-center">
            <Edit3 className="w-5 h-5 mr-2 text-green-500" />
            Personal Notes
          </h3>
          
          <textarea
            value={personalNotes}
            onChange={(e) => setPersonalNotes(e.target.value)}
            className="w-full h-32 p-3 border border-gray-200 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm resize-none focus:outline-none focus:ring-2 focus:ring-green-500"
            placeholder="Add your personal thoughts, questions, or additional notes..."
          />
        </div>

        {/* Related Resources */}
        <div className="bg-white dark:bg-gray-800 rounded-xl p-4 mb-6 shadow-sm">
          <h3 className="font-semibold text-gray-900 dark:text-white mb-4">Related Resources</h3>
          
          <div className="space-y-3">
            <button className="w-full p-3 bg-gray-50 dark:bg-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 rounded-lg text-left flex items-center justify-between">
              <div className="flex items-center space-x-3">
                <FileText className="w-5 h-5 text-blue-500" />
                <div>
                  <p className="font-medium text-gray-900 dark:text-white">Diabetes Diet Chart</p>
                  <p className="text-sm text-gray-600 dark:text-gray-300">Recommended meal plans and portions</p>
                </div>
              </div>
              <Download className="w-4 h-4 text-gray-400" />
            </button>

            <button className="w-full p-3 bg-gray-50 dark:bg-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 rounded-lg text-left flex items-center justify-between">
              <div className="flex items-center space-x-3">
                <FileText className="w-5 h-5 text-green-500" />
                <div>
                  <p className="font-medium text-gray-900 dark:text-white">Exercise Guidelines</p>
                  <p className="text-sm text-gray-600 dark:text-gray-300">Safe workout routines for diabetics</p>
                </div>
              </div>
              <Download className="w-4 h-4 text-gray-400" />
            </button>

            <button className="w-full p-3 bg-gray-50 dark:bg-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 rounded-lg text-left flex items-center justify-between">
              <div className="flex items-center space-x-3">
                <FileText className="w-5 h-5 text-purple-500" />
                <div>
                  <p className="font-medium text-gray-900 dark:text-white">Blood Sugar Log Template</p>
                  <p className="text-sm text-gray-600 dark:text-gray-300">Track your daily glucose readings</p>
                </div>
              </div>
              <Download className="w-4 h-4 text-gray-400" />
            </button>
          </div>
        </div>

        {/* Save to LifeLog */}
        <div className="bg-gradient-to-r from-green-50 to-blue-50 dark:from-green-900/30 dark:to-blue-900/30 border border-green-200 dark:border-green-800 rounded-xl p-4 mb-6">
          <div className="flex items-start space-x-3">
            <Heart className="w-6 h-6 text-green-600 dark:text-green-400 mt-1" />
            <div className="flex-1">
              <h3 className="font-semibold text-green-900 dark:text-green-100 mb-2">Auto-Save to LifeLog</h3>
              <p className="text-sm text-green-800 dark:text-green-200 mb-3">
                These notes are automatically saved to your LifeLog for future reference. 
                You can access them anytime from your health records.
              </p>
              <div className="flex items-center space-x-2">
                <CheckCircle className="w-4 h-4 text-green-600 dark:text-green-400" />
                <span className="text-sm text-green-700 dark:text-green-300">Saved to Medical Records</span>
              </div>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        {isEditing && (
          <div className="flex space-x-3">
            <Button
              variant="primary"
              className="flex-1"
              onClick={handleSaveNotes}
            >
              <Save className="w-4 h-4 mr-2" />
              Save Changes
            </Button>
            <Button
              variant="outline"
              onClick={() => setIsEditing(false)}
            >
              Cancel
            </Button>
          </div>
        )}
      </div>

      <BottomNavigation />
    </div>
  )
}